name: genre_classification
channels:
  - defaults
dependencies:
  - python=3.9.1
  - pip
  - pip:
      - requests
      - wandb
      - mlflow
      - hydra-core==1.0.6
      - hydra-joblib-launcher==1.1.2
